// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq0hk71CGTiHPrzdHxuou9cwxkHyifH0',
    appId: '1:546715749052:web:d6f4bd37d7a33524ffdeb9',
    messagingSenderId: '546715749052',
    projectId: 'logbook-3ab30',
    authDomain: 'logbook-3ab30.firebaseapp.com',
    storageBucket: 'logbook-3ab30.appspot.com',
    measurementId: 'G-7D6REHQ7RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjD6K7kldvOrwfScrotlr_krkUswwF9Uo',
    appId: '1:546715749052:android:c193b7047e5d38b8ffdeb9',
    messagingSenderId: '546715749052',
    projectId: 'logbook-3ab30',
    storageBucket: 'logbook-3ab30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxWmW8U-1SI_waQ0-FdKwtnoD5a8fbx4',
    appId: '1:546715749052:ios:9d3a4e24a6dc4fa7ffdeb9',
    messagingSenderId: '546715749052',
    projectId: 'logbook-3ab30',
    storageBucket: 'logbook-3ab30.appspot.com',
    iosBundleId: 'com.example.logbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYxWmW8U-1SI_waQ0-FdKwtnoD5a8fbx4',
    appId: '1:546715749052:ios:9d3a4e24a6dc4fa7ffdeb9',
    messagingSenderId: '546715749052',
    projectId: 'logbook-3ab30',
    storageBucket: 'logbook-3ab30.appspot.com',
    iosBundleId: 'com.example.logbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARq0hk71CGTiHPrzdHxuou9cwxkHyifH0',
    appId: '1:546715749052:web:6ae1e627046d5012ffdeb9',
    messagingSenderId: '546715749052',
    projectId: 'logbook-3ab30',
    authDomain: 'logbook-3ab30.firebaseapp.com',
    storageBucket: 'logbook-3ab30.appspot.com',
    measurementId: 'G-Z6T0TERFZY',
  );
}
